export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

/*
 * Book
 */

export const BOOK_FETCH_REQUEST = 'BOOK_FETCH_REQUEST';
export const BOOK_FETCH_SUCCESS = 'BOOK_FETCH_SUCCESS';
export const BOOK_FETCH_ERROR = 'BOOK_FETCH_ERROR';

export const BOOK_FETCH_BY_ID_REQUEST = 'BOOK_FETCH_BY_ID_REQUEST';
export const BOOK_FETCH_BY_ID_SUCCESS = 'BOOK_FETCH_BY_ID_SUCCESS';
export const BOOK_FETCH_BY_ID_ERROR = 'BOOK_FETCH_BY_ID_ERROR';

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_ERROR = 'BOOK_CREATE_ERROR';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_ERROR = 'BOOK_DELETE_ERROR';

export const BOOK_GET_BOOKMARK_REQUEST = 'BOOK_GET_BOOKMARK_REQUEST';
export const BOOK_GET_BOOKMARK_SUCCESS = 'BOOK_GET_BOOKMARK_SUCCESS';
export const BOOK_GET_BOOKMARK_ERROR = 'BOOK_GET_BOOKMARK_ERROR';

export const BOOK_BOOKMARK_PAGE = 'BOOK_BOOKMARK_PAGE';
export const BOOK_UN_BOOKMARK_PAGE = 'BOOK_UN_BOOKMARK_PAGE';

export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const SET_BOOK_COLLECTION_INFO = 'SET_BOOK_COLLECTION_INFO';

export const SAVE_BOOK = 'SAVE_BOOK';

/*
 * Book Collection
 */
export const BOOK_COLLECTION_FETCH_REQUEST = 'BOOK_COLLECTION_FETCH_REQUEST';
export const BOOK_COLLECTION_FETCH_SUCCESS = 'BOOK_COLLECTION_FETCH_SUCCESS';
export const BOOK_COLLECTION_FETCH_ERROR = 'BOOK_COLLECTION_FETCH_ERROR';

export const BOOK_COLLECTION_FETCH_BY_ID_REQUEST =
  'BOOK_COLLECTION_FETCH_BY_ID_REQUEST';
export const BOOK_COLLECTION_FETCH_BY_ID_SUCCESS =
  'BOOK_COLLECTION_FETCH_BY_ID_SUCCESS';
export const BOOK_COLLECTION_FETCH_BY_ID_ERROR =
  'BOOK_COLLECTION_FETCH_BY_ID_ERROR';

export const BOOK_COLLECTION_CREATE_REQUEST = 'BOOK_COLLECTION_CREATE_REQUEST';
export const BOOK_COLLECTION_CREATE_SUCCESS = 'BOOK_COLLECTION_CREATE_SUCCESS';
export const BOOK_COLLECTION_CREATE_ERROR = 'BOOK_COLLECTION_CREATE_ERROR';

/*
 * Pagoda
 */
export const PAGODA_FETCH_REQUEST = 'PAGODA_FETCH_REQUEST';
export const PAGODA_FETCH_SUCCESS = 'PAGODA_FETCH_SUCCESS';
export const PAGODA_FETCH_ERROR = 'PAGODA_FETCH_ERROR';

export const PAGODA_FETCH_BY_ID_REQUEST = 'PAGODA_FETCH_BY_ID_REQUEST';
export const PAGODA_FETCH_BY_ID_SUCCESS = 'PAGODA_FETCH_BY_ID_SUCCESS';
export const PAGODA_FETCH_BY_ID_ERROR = 'PAGODA_FETCH_BY_ID_ERROR';

export const PAGODA_CREATE_REQUEST = 'PAGODA_CREATE_REQUEST';
export const PAGODA_CREATE_SUCCESS = 'PAGODA_CREATE_SUCCESS';
export const PAGODA_CREATE_ERROR = 'PAGODA_CREATE_ERROR';

/*
 * Audio
 */
export const AUDIO_FETCH_REQUEST = 'AUDIO_FETCH_REQUEST';
export const AUDIO_FETCH_SUCCESS = 'AUDIO_FETCH_SUCCESS';
export const AUDIO_FETCH_ERROR = 'AUDIO_FETCH_ERROR';

export const AUDIO_FETCH_BY_ID_REQUEST = 'AUDIO_FETCH_BY_ID_REQUEST';
export const AUDIO_FETCH_BY_ID_SUCCESS = 'AUDIO_FETCH_BY_ID_SUCCESS';
export const AUDIO_FETCH_BY_ID_ERROR = 'AUDIO_FETCH_BY_ID_ERROR';

export const AUDIO_CREATE_REQUEST = 'AUDIO_CREATE_REQUEST';
export const AUDIO_CREATE_SUCCESS = 'AUDIO_CREATE_SUCCESS';
export const AUDIO_CREATE_ERROR = 'AUDIO_CREATE_ERROR';

export const AUDIO_DELETE_REQUEST = 'AUDIO_DELETE_REQUEST';
export const AUDIO_DELETE_SUCCESS = 'AUDIO_DELETE_SUCCESS';
export const AUDIO_DELETE_ERROR = 'AUDIO_DELETE_ERROR';

/*
 * Audio Category
 */
export const AUDIO_CATEGORY_FETCH_REQUEST = 'AUDIO_CATEGORY_FETCH_REQUEST';
export const AUDIO_CATEGORY_FETCH_SUCCESS = 'AUDIO_CATEGORY_FETCH_SUCCESS';
export const AUDIO_CATEGORY_FETCH_ERROR = 'AUDIO_CATEGORY_FETCH_ERROR';

export const AUDIO_CATEGORY_FETCH_BY_ID_REQUEST =
  'AUDIO_CATEGORY_FETCH_BY_ID_REQUEST';
export const AUDIO_CATEGORY_FETCH_BY_ID_SUCCESS =
  'AUDIO_CATEGORY_FETCH_BY_ID_SUCCESS';
export const AUDIO_CATEGORY_FETCH_BY_ID_ERROR =
  'AUDIO_CATEGORY_FETCH_BY_ID_ERROR';

export const SET_AUDIO_CATEGORY = 'SET_AUDIO_CATEGORY';

export const AUDIO_CATEGORY_CREATE_REQUEST = 'AUDIO_CATEGORY_CREATE_REQUEST';
export const AUDIO_CATEGORY_CREATE_SUCCESS = 'AUDIO_CATEGORY_CREATE_SUCCESS';
export const AUDIO_CATEGORY_CREATE_ERROR = 'AUDIO_CATEGORY_CREATE_ERROR';

/*
 * Sub Audio Category
 */
export const SUB_AUDIO_CATEGORY_FETCH_REQUEST =
  'SUB_AUDIO_CATEGORY_FETCH_REQUEST';
export const SUB_AUDIO_CATEGORY_FETCH_SUCCESS =
  'SUB_AUDIO_CATEGORY_FETCH_SUCCESS';
export const SUB_AUDIO_CATEGORY_FETCH_ERROR = 'SUB_AUDIO_CATEGORY_FETCH_ERROR';

export const SUB_AUDIO_CATEGORY_FETCH_BY_ID_REQUEST =
  'SUB_AUDIO_CATEGORY_FETCH_BY_ID_REQUEST';
export const SUB_AUDIO_CATEGORY_FETCH_BY_ID_SUCCESS =
  'SUB_AUDIO_CATEGORY_FETCH_BY_ID_SUCCESS';
export const SUB_AUDIO_CATEGORY_FETCH_BY_ID_ERROR =
  'SUB_AUDIO_CATEGORY_FETCH_BY_ID_ERROR';

export const SUB_AUDIO_CATEGORY_CREATE_REQUEST =
  'SUB_AUDIO_CATEGORY_CREATE_REQUEST';
export const SUB_AUDIO_CATEGORY_CREATE_SUCCESS =
  'SUB_AUDIO_CATEGORY_CREATE_SUCCESS';
export const SUB_AUDIO_CATEGORY_CREATE_ERROR =
  'SUB_AUDIO_CATEGORY_CREATE_ERROR';

/*
 * Video
 */
export const VIDEO_FETCH_REQUEST = 'VIDEO_FETCH_REQUEST';
export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS';
export const VIDEO_FETCH_ERROR = 'VIDEO_FETCH_ERROR';

export const VIDEO_FETCH_BY_ID_REQUEST = 'VIDEO_FETCH_BY_ID_REQUEST';
export const VIDEO_FETCH_BY_ID_SUCCESS = 'VIDEO_FETCH_BY_ID_SUCCESS';
export const VIDEO_FETCH_BY_ID_ERROR = 'VIDEO_FETCH_BY_ID_ERROR';

export const VIDEO_CREATE_REQUEST = 'VIDEO_CREATE_REQUEST';
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS';
export const VIDEO_CREATE_ERROR = 'VIDEO_CREATE_ERROR';

/*
 * Audio Category
 */
export const VIDEO_CATEGORY_FETCH_REQUEST = 'VIDEO_CATEGORY_FETCH_REQUEST';
export const VIDEO_CATEGORY_FETCH_SUCCESS = 'VIDEO_CATEGORY_FETCH_SUCCESS';
export const VIDEO_CATEGORY_FETCH_ERROR = 'VIDEO_CATEGORY_FETCH_ERROR';

export const VIDEO_CATEGORY_FETCH_BY_ID_REQUEST =
  'VIDEO_CATEGORY_FETCH_BY_ID_REQUEST';
export const VIDEO_CATEGORY_FETCH_BY_ID_SUCCESS =
  'VIDEO_CATEGORY_FETCH_BY_ID_SUCCESS';
export const VIDEO_CATEGORY_FETCH_BY_ID_ERROR =
  'VIDEO_CATEGORY_FETCH_BY_ID_ERROR';

export const VIDEO_CATEGORY_CREATE_REQUEST = 'VIDEO_CATEGORY_CREATE_REQUEST';
export const VIDEO_CATEGORY_CREATE_SUCCESS = 'VIDEO_CATEGORY_CREATE_SUCCESS';
export const VIDEO_CATEGORY_CREATE_ERROR = 'VIDEO_CATEGORY_CREATE_ERROR';

export const PLAY_REQUEST = 'PLAY_REQUEST';
export const PLAY_SUCCESS = 'PLAY_SUCCESS';
export const PLAY_ERROR = 'PLAY_ERROR';

export const SAVE_AUDIO = 'SAVE_AUDIO';
